# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentpack" do
  version "0.3.21"

  on_macos do
    on_arm do
      sha256 "6c054dad8664ce57dc4ff67f7035737c1395a718673d4dc8d80d8f86ea6ce6cc"
      url "https://github.com/OlegHQ/agentpack/releases/download/v#{version}/agentpack_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "20e0288dd7f5b3aad75d68a37c0f7bd670be5bb3c5ad24e38bb15c6da272e910"
      url "https://github.com/OlegHQ/agentpack/releases/download/v#{version}/agentpack_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fd5301b9188a6a2dccc4d57d407b47213138dd80b360cc2086bd383df3d349c1"
      url "https://github.com/OlegHQ/agentpack/releases/download/v#{version}/agentpack_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "56b0bcf11be33da7a5d214c97a7081f38fbc613074c31af28bced665f3fca519"
      url "https://github.com/OlegHQ/agentpack/releases/download/v#{version}/agentpack_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentpack"
  desc "Pin and stage agent skills and plugins reproducibly"
  homepage "https://github.com/OlegHQ/agentpack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentpack"

  # No zap stanza required
end
