# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentpack" do
  version "0.3.29"

  on_macos do
    on_arm do
      sha256 "006576a7896037da1f83be8a1d577f8dbbf9fef3a3cb39480130bf498754234d"
      url "https://github.com/OlegHQ/agentpack/releases/download/v#{version}/agentpack_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "74d20db32870b51baa92886742ca13f8e33d2f61ff5f8faaf65073ca3f2bdbfb"
      url "https://github.com/OlegHQ/agentpack/releases/download/v#{version}/agentpack_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3d5e942243e4e15279aeb5e841e93e417156d397cee5873c34121e7ca526c32f"
      url "https://github.com/OlegHQ/agentpack/releases/download/v#{version}/agentpack_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5b88af8ae4fae306655c317bc5a278faf8e08a0e33d20f227457b2d68e58f2d8"
      url "https://github.com/OlegHQ/agentpack/releases/download/v#{version}/agentpack_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentpack"
  desc "Pin and stage agent skills and plugins reproducibly"
  homepage "https://github.com/OlegHQ/agentpack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentpack"

  # No zap stanza required
end
