# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentpack" do
  version "0.3.31"

  on_macos do
    on_arm do
      sha256 "9a8a10920184aeb963fd77986eff34f7c36f1b8fb71d67f81037bd403bd65721"
      url "https://github.com/OlegHQ/agentpack/releases/download/v#{version}/agentpack_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4eb705be87b020153812115a31c107b370d9432199eae16bddec358f6164b8da"
      url "https://github.com/OlegHQ/agentpack/releases/download/v#{version}/agentpack_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1b7ee832552571fd07e56237ef141a3dd7fcc1ff356464f458da4dfc854f4d6e"
      url "https://github.com/OlegHQ/agentpack/releases/download/v#{version}/agentpack_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "745bca794700e187de7601afea3e8dc10d742be921524812e41f63658696d43d"
      url "https://github.com/OlegHQ/agentpack/releases/download/v#{version}/agentpack_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentpack"
  desc "Pin and stage agent skills and plugins reproducibly"
  homepage "https://github.com/OlegHQ/agentpack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentpack"

  # No zap stanza required
end
